export const Errors = {
    400: 'Bad request',
    401: 'Unauthorized',
    403: 'Forbidden',
    404: 'Not found',
    500: 'Internal server error',
    501: 'Not implemented',
    502: 'Bad gateway',
    503: 'Service unavailable',
    504: 'Gateway timeout',
    505: 'HTTP version not supported',
    506: 'Variant also negotiates',
    507: 'Insufficient storage',
    508: 'Loop detected',
    510: 'Not extended',
    511: 'Network authentication required',
    520: 'Unknown error',
    521: 'Web server is down',
    522: 'Connection timed out',
    523: 'Origin is unreachable',
    524: 'A timeout occurred',
    525: 'SSL handshake failed',
}